spring:
  application:
    name: revify-mono
  config:
    import:
      - classpath:messaging.yml
      - classpath:keycloak.yml
      - classpath:payment.yml
      - classpath:files.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8085}/realms/revify/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 40MB
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: root
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/revify?currentSchema=system}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: system
  data:
    jpa:
      repositories:
        enabled: true
    mongodb:
      database: revify
      port: ${MONGODB_PORT:27017}
      host: ${MONGODB_HOST:localhost}
      username: mongo
      password: bongo
      auto-index-creation: true
      authentication-database: admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: revify-consumers
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: record

keycloak:
  client-id: ${KEYCLOAK_ID:client-id}
  client-secret: ${KEYCLOAK_SECRET:client-secret}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8085}/auth
  realm: ${KEYCLOAK_REALM_NAME:realm-name}

server:
  port: 8001
  http2:
    enabled: true
logging:
  level:
    org.apache.kafka: WARN
    org.springframework.web: DEBUG