spring:
  application:
    name: revify-mono
  config:
    import:
      - classpath:messaging.yml
      - classpath:keycloak.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8085}/realms/revify/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: postgres
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/revify?currentSchema=system}
    hikari:
      schema: system
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/revify?currentSchema=system}
    jpa:
      hibernate:

        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      database: revify-mono
      port: ${MONGODB_PORT:27019}
      host: ${MONGODB_HOST:localhost}
      username: mongo
      password: bongo
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: revify-consumers
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: record
revify:
  keycloak:
    grpc: ${REVIFY_KEYCLOAK_GRPC:localhost:7004}

keycloak:
  client-id: ${KEYCLOAK_ID:client-id}
  client-secret: ${KEYCLOAK_SECRET:client-secret}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8085}/auth
  realm: ${KEYCLOAK_REALM_NAME:realm-name}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    enabled: true
    path: /swagger
    operations-sorter: method

grpc:
  server:
    port: 8002
server:
  port: 8001
  http2:
    enabled: true
logging:
  level:
    org.springframework: info
    lombok: debug